# Generated by Django 2.0.6 on 2018-06-23 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 6, 23, 12, 59, 10, 44232, tzinfo=utc))),
                ('montant', models.FloatField()),
                ('est_panier', models.BooleanField(default=False)),
                ('envoie', models.BooleanField(default=True)),
                ('est_envoyee', models.BooleanField(default=False)),
                ('est_archivee', models.BooleanField(default=False)),
                ('est_payee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContenuCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cepage', models.TextField(blank=True, null=True)),
                ('notes_degustation', models.TextField(blank=True, null=True)),
                ('accords', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('date_ajout', models.DateField(default=django.utils.timezone.now)),
                ('prix', models.FloatField()),
                ('est_promo', models.BooleanField(default=False)),
                ('debut_promo', models.DateField(blank=True, null=True)),
                ('fin_promo', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('poid', models.FloatField(null=True, verbose_name='poid en gramme')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='magasin.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypesProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.SousCategorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='magasin.TypesProduit'),
        ),
        migrations.AddField(
            model_name='contenucommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Produit'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='sous_cats',
            field=models.ManyToManyField(to='magasin.SousCategorie'),
        ),
    ]
