# Generated by Django 2.0.6 on 2018-06-26 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_auto_20180626_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 14, 0, 5, 79714, tzinfo=utc)),
        ),
    ]
