# Generated by Django 2.0.6 on 2018-06-26 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_auto_20180626_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 14, 1, 38, 449891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contenucommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.Commande'),
        ),
    ]
