# Generated by Django 2.0.6 on 2018-06-29 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_auto_20180627_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(default='', upload_to='uploads/produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 7, 23, 52, 548691, tzinfo=utc)),
        ),
    ]
