# Generated by Django 2.0.6 on 2018-06-29 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_auto_20180629_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 10, 3, 33, 492188, tzinfo=utc)),
        ),
    ]
