# Generated by Django 2.0.6 on 2018-07-03 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_auto_20180629_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 15, 25, 50, 901635, tzinfo=utc)),
        ),
    ]
