# Generated by Django 2.0.6 on 2018-07-04 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0016_auto_20180703_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='sous_cats',
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='magasin.Categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 16, 2, 43, 583852, tzinfo=utc)),
        ),
    ]
