# Generated by Django 2.0.6 on 2018-07-06 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0017_auto_20180704_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesproduit',
            name='categories',
            field=models.ManyToManyField(to='magasin.Categorie'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 12, 35, 47, 292241, tzinfo=utc)),
        ),
    ]
