# Generated by Django 2.0.6 on 2018-07-06 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0018_auto_20180706_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 15, 58, 16, 344878, tzinfo=utc)),
        ),
    ]
