# Generated by Django 2.0.6 on 2018-07-17 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0019_auto_20180706_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 10, 59, 7, 702291, tzinfo=utc)),
        ),
    ]
