# Generated by Django 2.0.6 on 2018-07-17 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0020_auto_20180717_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 11, 16, 11, 111399, tzinfo=utc)),
        ),
    ]
