# Generated by Django 2.0.6 on 2018-07-25 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0021_auto_20180717_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 13, 22, 21, 196194, tzinfo=utc)),
        ),
    ]
