# Generated by Django 2.0.7 on 2018-07-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='description_perso',
            field=models.TextField(default=''),
        ),
    ]
