# Generated by Django 2.0.7 on 2018-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0002_fiche_description_perso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='description_perso',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='nom_perso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='prenom_perso',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
