# Generated by Django 2.0.7 on 2018-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0003_auto_20180707_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
