# Generated by Django 2.0.7 on 2018-07-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0005_fiche_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='when_the_light_go_down.Fiche')),
            ],
        ),
    ]
