# Generated by Django 2.0.7 on 2018-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0006_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='connaissance',
            field=models.IntegerField(default=10),
        ),
    ]
