# Generated by Django 2.0.7 on 2018-07-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0007_fiche_connaissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='when_the_light_go_down.Objets'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='perso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='when_the_light_go_down.Fiche'),
        ),
    ]
