# Generated by Django 2.0.7 on 2018-07-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0008_auto_20180720_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objets',
            new_name='Objet',
        ),
    ]
