# Generated by Django 2.0.7 on 2018-07-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0010_auto_20180720_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('orions', models.IntegerField()),
                ('argentions', models.IntegerField()),
                ('cuivrons', models.IntegerField()),
                ('donneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donneur', to='when_the_light_go_down.Fiche')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='when_the_light_go_down.Fiche')),
            ],
        ),
    ]
