# Generated by Django 2.0.7 on 2018-07-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when_the_light_go_down', '0011_echange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bourse',
            name='argentions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='cuivrons',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='orions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
